baseurl: "/ArtificiallyIntelligent"
show_downloads: true

collections:
        contributions:
                output: true
                defaults:
                        values:
                                layout: default


theme: jekyll-theme-slate
