baseurl: "/ArtificiallyIntelligent"
show_downloads: true

collections:
        contributions:
                output: true
                defaults:
                        values:
                                layout: default

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

theme: jekyll-theme-slate
